### PR TITLE
Correct f 15e ufc

### PR DESCRIPTION
**Pull request by davidp57**
Two changes:
- optimized by removing a string comparison on each tick (made that a boolean)
- changed the indexes for the UFC, they're wrong since last DCS update

### CODE REVIEW

**Comment by asherao** [comment]
does this change still need to be made with the recent merge?

**Comment by ExoLightFR** [comment]
No, except for the string comparison. No idea why there wasn't a boolean there in the first place?

**Comment by davidp57** [comment]
conflict solved ! @ExoLightFR I think the WSO index was still wrong in the master, can you confirm that it has to be 18 ?

**Comment by pbremondFR** [comment]
Let me boot up DCS to check it again, but I'm pretty sure the WSO's UFC exports correctly with index 18. I simply counted the indicator's indexes up until `F15E_Displays::ccUFC_Rear`.

**Comment by pbremondFR** [comment]
Yes, tested it again right now, can confirm that 18 is now the right indicator index for WSO UFC, not 21.

**Comment by davidp57** [comment]
ok, it's settled then; @asherao if you would be so kind as to merge this PR, it contains both the WSO index fix and the string to boolean optimization - and has no comflict

**Comment by ExoLightFR** [comment]
I'm still seeing the wrong WSO UFC indicator number, looks like it's still 21 instead of 18

**Pull request merged**
